import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, RefreshCw, Repeat2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../shared/api'

type TaskName = 'payroll' | 'insurance' | 'retirement' | 'other'
type Task = { required?: boolean; completedAt?: string | null; completedBy?: string }
type Change = { id: string; employeeName: string; employeeEmail: string; effectiveDate: string; reason: string; changes: { field: string; from: string; to: string }[]; tasks: Record<TaskName, Task>; createdBy: string }

const taskLabels: Record<TaskName, string> = { payroll: 'Payroll', insurance: 'Insurance', retirement: '401(k)', other: 'Other HR Follow-up' }
const displayDate = (value: string) => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString('en-US') : '--'

export default function EmploymentChange() {
  const [records, setRecords] = useState<Change[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const load = () => { setLoading(true); setError(''); api.get('/hr-platform/employment-changes').then(response => setRecords(response.data || [])).catch(error => setError(error.response?.data?.error || 'Employment Change records could not be loaded.')).finally(() => setLoading(false)) }
  useEffect(load, [])
  const filtered = useMemo(() => records.filter(record => `${record.employeeName} ${record.employeeEmail} ${record.reason}`.toLowerCase().includes(query.trim().toLowerCase())), [records, query])
  const pending = records.flatMap(record => (Object.keys(taskLabels) as TaskName[]).filter(task => record.tasks?.[task]?.required && !record.tasks?.[task]?.completedAt).map(task => ({ record, task }))).sort((a, b) => a.record.effectiveDate.localeCompare(b.record.effectiveDate))
  async function complete(record: Change, task: TaskName) { if (!window.confirm(`Confirm that the ${taskLabels[task]} action has been completed for ${record.employeeName}.`)) return; try { await api.put(`/hr-platform/employment-changes/${record.id}/tasks/${task}`); await load() } catch (error: any) { setError(error.response?.data?.error || 'The task could not be completed.') } }
  return <div className="space-y-7 pb-12">
    <section className="rounded-3xl bg-gradient-to-br from-slate-950 via-blue-950 to-cyan-800 px-7 py-8 text-white shadow-2xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-100" to="/hr-platform"><ArrowLeft className="h-4 w-4" />Back to HR Platform</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-wider"><Repeat2 className="h-4 w-4" />Employee Lifecycle</div><h1 className="mt-3 text-4xl font-semibold">Employment Change</h1><p className="mt-2 text-sm text-blue-100">Track employee information changes and required Payroll, Insurance, 401(k), or HR follow-up.</p></div><button className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-bold text-blue-950" onClick={load}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div></section>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <section className="overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-lg"><div className="border-b border-blue-100 bg-blue-50 px-6 py-5"><h2 className="text-xl font-bold text-blue-950">Employment Change Action Calendar</h2><p className="mt-1 text-sm text-blue-700">Every unfinished task remains here until action is confirmed.</p></div><div className="max-h-80 overflow-auto"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-slate-100 text-left text-xs uppercase text-slate-600"><tr><th className="px-5 py-3">Effective Date</th><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{pending.map(({ record, task }) => <tr className="border-t" key={`${record.id}-${task}`}><td className="px-5 py-3 font-semibold">{displayDate(record.effectiveDate)}</td><td className="px-5 py-3">{record.employeeName}</td><td className="px-5 py-3">{taskLabels[task]}</td><td className="px-5 py-3"><button className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white" onClick={() => complete(record, task)}>Confirm Action Taken</button></td></tr>)}{!pending.length && <tr><td className="px-5 py-8 text-center text-slate-500" colSpan={4}>No pending employment change actions.</td></tr>}</tbody></table></div></section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-6 py-5"><div><h2 className="text-xl font-bold">All Employment Changes</h2><p className="mt-1 text-sm text-slate-600">Current and completed change history.</p></div><input className="rounded-lg border border-slate-300 px-3 py-2 text-sm" placeholder="Search employee or reason..." value={query} onChange={event => setQuery(event.target.value)} /></div><div className="overflow-auto"><table className="min-w-[1200px] text-sm"><thead className="bg-slate-100 text-left text-xs uppercase text-slate-600"><tr><th className="sticky left-0 z-10 bg-slate-100 px-4 py-3">Employee</th><th className="px-4 py-3">Effective Date</th><th className="px-4 py-3">Information Changed</th><th className="px-4 py-3">Reason</th>{(Object.keys(taskLabels) as TaskName[]).map(task => <th className="px-4 py-3" key={task}>{taskLabels[task]}</th>)}</tr></thead><tbody>{filtered.map(record => <tr className="border-t"><td className="sticky left-0 bg-white px-4 py-3 font-bold">{record.employeeName}<div className="text-xs font-normal text-slate-500">{record.employeeEmail}</div></td><td className="px-4 py-3">{displayDate(record.effectiveDate)}</td><td className="px-4 py-3">{record.changes.map(change => <div key={change.field}><b>{change.field}:</b> {change.from || '--'} → {change.to || '--'}</div>)}</td><td className="px-4 py-3">{record.reason}</td>{(Object.keys(taskLabels) as TaskName[]).map(task => <td className="px-4 py-3" key={task}>{!record.tasks?.[task]?.required ? '--' : record.tasks[task].completedAt ? <span className="font-bold text-emerald-700">Completed</span> : <button className="rounded-lg border border-blue-300 px-3 py-1.5 text-xs font-bold text-blue-700" onClick={() => complete(record, task)}>Action Needed</button>}</td>)}</tr>)}{!filtered.length && <tr><td className="px-5 py-10 text-center text-slate-500" colSpan={8}>No employment changes found.</td></tr>}</tbody></table></div></section>
  </div>
}
